//////////////////////////////////////////////////////////////////////////////////
//    EOM.hh, part of  imsrg++
//    Copyright (C) 2021  Ragnar Stroberg
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License along
//    with this program; if not, write to the Free Software Foundation, Inc.,
//    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
///////////////////////////////////////////////////////////////////////////////////

#ifndef EOM_hh
#define EOM_hh 1

#include "Generator.hh"
#include "ModelSpace.hh"
#include "Operator.hh"
#include <string>
#include <tuple>
#include <vector>

class EOM {
public:
  // essential fields
  ModelSpace *modelspace; ///< Pointer to the associated modelspace
  Operator Hs;
  /// Copy of Hs after force_decouple (vv kept). Used for Delta-E checks /
  /// ArnoldiSolveH2. Set by PrepareHamiltonianForArnoldi() or RunMR().
  Operator Hs_full;
  bool have_Hs_full = false;
  // JPT for the EOM, angular momentum, parity and isospin change
  int J2 = 0;
  int parity = 0;
  int itz = 0;

  /// true when an rdm / tdm_file was supplied at construction (MR mode).
  /// false for plain single-reference EOM.
  bool is_multiref = false;

  // The following are used for the multi-reference EOM only
  ModelSpace rdm_modelspace; ///< Owned modelspace for rdm when built from a tdm_file
  ModelSpace *rdm_ms = nullptr; ///< Points to rdm_modelspace (file) or modelspace (Hs)
  std::vector<int> hs_to_rdm_orb; ///< Map: Hs orbit index -> rdm orbit index (-1 if absent)
  Operator rdm;
  arma::sp_mat Nkernel;
  arma::sp_mat Prj_kernel;
  /// Canonical transform X = U s^{-1/2} (N x M) from BuildCanonicalTransform.
  arma::mat X_canon;
  bool have_X_canon = false;
  // arma::mat Nkernel;

  arma::vec Energies;
  // configurations
  std::vector<std::array<index_t, 4>> eom_confs;
  index_t qv_start, qv_end, qv_dim;
  index_t ph_start, ph_end, ph_dim;
  index_t ppvv_start, ppvv_end, ppvv_dim;
  index_t pphv_start, pphv_end, pphv_dim;
  index_t pphh_start, pphh_end, pphh_dim;
  size_t channel;
  index_t eom_dims = 0;
  bool arnoldi_use_projection = true;
  bool arnoldi_check_expectation = false;
  bool arnoldi_print_timing = false;
  bool arnoldi_monitor_ortho = true;
  /// Include DcomMultiref ([S,[H,S]]_3b) in the Hall matrix.
  /// Default true: Krylov is generated by Htc (2b of [H,S]) only — no 3b
  /// χ′ exists — but the physical kernel is Q = Htc + Dcom; Hall must use
  /// both so Ritz eigenvalues match ExpectationValue (= Q/N).
  /// Set false only for H2-only debugging (then ExpectationValue will differ).
  bool arnoldi_use_h3 = true;
  /// If true, prefer ΔE >= arnoldi_soft_floor when packing state_want roots.
  /// Default false: return the lowest Ritz values (do not discard negatives).
  bool arnoldi_prefer_positive = false;
  /// Soft-mode floor (MeV) used only when arnoldi_prefer_positive is true.
  double arnoldi_soft_floor = 0.0;
  /// Absolute energy stagnation tol (MeV) over arnoldi_stable_window steps.
  double arnoldi_energy_tol = 1e-3;
  /// Lanczos-style residual estimate tol: rho_k ~ beta * |s_{m k}| (MeV).
  double arnoldi_resid_tol = 1e-3;
  /// Warn if max |<v_i|v_j>| (i!=j) exceeds this after GS.
  double arnoldi_ortho_warn = 1e-6;
  /// Stop: orthogonality lost; Ritz values no longer trustworthy.
  double arnoldi_ortho_fail = 1e-3;
  int arnoldi_stable_window = 3;
  bool use_reference_energy_shift = false;
  double reference_energy_shift = 0.0;
  /// Include valence 3-body RDM (TRBTD) in Nkernel / GetVSEOM_Overlap_multiref.
  /// Default false: ρ₃ diagrams currently disagree with the commutator path on He8.
  bool use_rdm3 = false;

  /// Which EOM configuration blocks to include (default: all).
  /// Call SetIncludeConfigs before ConstructConfigs / ladders.
  ///   qv   = 1b excluded←valence
  ///   ph   = 1b (v∪q)←core
  ///   ppvv = 2b qqvv (bra qq∪qv, ket vv)   — aka qqvv
  ///   pphv = 2b qqhv (bra qq∪qv∪vv, ket vc) — aka qqhv
  ///   pphh = 2b (bra qq∪qv∪vv, ket cc)
  bool include_qv   = true;
  bool include_ph   = true;
  bool include_ppvv = true;
  bool include_pphv = true;
  bool include_pphh = true;
  double dcom_time_ladder = 0.0;
  double dcom_time_223_231 = 0.0;
  double dcom_time_223_232 = 0.0;
  double dcom_time_223_132 = 0.0;
  double dcom_time_overlap = 0.0;
  int dcom_profile_calls = 0;

  // Methods
  EOM(Operator &Hs, Operator &rdm, int J2, int parity, int itz);
  EOM(Operator &Hs, const std::string &tdm_file, int J2, int parity, int itz);
  EOM(Operator &Hs, int J2, int parity, int itz);

  void EraseValence(Operator &H); ///< DISABLED no-op (do not drop vv)
  void EraseQspace(Operator &H);
  void force_decouple(Operator &H);
  /// force_decouple + set Hs_full; keeps vv; clears any E_val shift.
  void PrepareHamiltonianForArnoldi();
  void SetArnoldiUseProjection(bool use_projection) { arnoldi_use_projection = use_projection; }
  void SetArnoldiCheckExpectation(bool check_expectation) { arnoldi_check_expectation = check_expectation; }
  void SetArnoldiPrintTiming(bool print_timing) { arnoldi_print_timing = print_timing; }
  void SetArnoldiMonitorOrtho(bool monitor) { arnoldi_monitor_ortho = monitor; }
  void SetArnoldiUseH3(bool use_h3) { arnoldi_use_h3 = use_h3; }
  void SetArnoldiPreferPositive(bool prefer) { arnoldi_prefer_positive = prefer; }
  void SetArnoldiSoftFloor(double floor_mev) { arnoldi_soft_floor = floor_mev; }
  void SetArnoldiEnergyTol(double tol) { arnoldi_energy_tol = tol; }
  void SetArnoldiResidTol(double tol) { arnoldi_resid_tol = tol; }
  void SetArnoldiOrthoWarn(double tol) { arnoldi_ortho_warn = tol; }
  void SetArnoldiOrthoFail(double tol) { arnoldi_ortho_fail = tol; }
  void SetArnoldiStableWindow(int n) { arnoldi_stable_window = (n > 1) ? n : 1; }
  /// Toggle valence ρ₃ (TRBTD) in norm / overlap. Call before ConstructNormMatrix.
  void SetUseRdm3(bool use) { use_rdm3 = use; }
  bool GetUseRdm3() const { return use_rdm3; }
  /// Select which config blocks enter ConstructConfigs / ladders / Nkernel.
  /// Must be called before ConstructConfigs (and ideally before ladders).
  void SetIncludeConfigs(bool qv, bool ph, bool ppvv, bool pphv, bool pphh);
  void PrintIncludeConfigs() const;
  /// Legacy API: EraseValence + E_val*N was incorrect and is disabled.
  /// ClearReferenceEnergyShift / GetReferenceEnergyShift remain for compatibility
  /// (shift is always zero in production paths).
  void SetReferenceEnergyShift(double energy) { reference_energy_shift = energy; use_reference_energy_shift = true; }
  void ClearReferenceEnergyShift() { reference_energy_shift = 0.0; use_reference_energy_shift = false; }
  double GetReferenceEnergyShift() const { return use_reference_energy_shift ? reference_energy_shift : 0.0; }

  double GetVSEOM_Overlap_single(Operator &H1, Operator &H2);
  double GetVSEOM_Overlap_multiref(Operator &H);
  Operator GetVSEOM_ladder_single(Operator &H, int herm);
  Operator GetVSEOM_ladder_multiref(Operator &H, int herm);

  void ConstructConfigs();
  void PrintConfigs();
  void ShowModel();
  void ConstructNormMatrix();
  void ConstructProjectMatrix();
  /// Canonical orthogonalization of Nkernel (Szabo–Ostlund):
  ///   N U = U s, keep s_k >= eps * s_max, X = U_sub * s_sub^{-1/2}.
  /// Returns M = number of retained modes. Stores X in X_canon (N x M).
  int BuildCanonicalTransform(double eps = 1e-8);

  double Core_Diagram(size_t a, size_t b, size_t c, size_t d, size_t e,
                      size_t f, double j1, double j2);
  // Debug/inspection helper: return the direct-term 3-body diagram entries before
  // RDM contraction. The public scalar API applies the same direct-only convention.
  std::vector<std::tuple<size_t,size_t,size_t,double>> ThreeBody_Diagram_Entries(size_t a, size_t b, size_t c,
                           size_t d, size_t e, size_t f, size_t g, double j0,
                           double j2);
  // Main API: compute the direct term, apply the local half/full convention,
  // and contract it with the 3-body RDM.
  double ThreeBody_Diagram(size_t a, size_t b, size_t c,
                           size_t d, size_t e, size_t f,
                           size_t g, double j0, double j2);

  arma::vec GetEnergies();
  void SqrtMat(arma::mat &Amat, size_t n);
  void ProjectOprator(Operator &Qin);
  void block_svd(std::vector<int> &coupled_vector);
  double ComputeNorm(Operator &Op1, Operator &Op2);
  /// Pack EOM config amplitudes of Op into a dense vector (length eom_dims).
  arma::vec FlattenOperator(Operator &Op) const;
  /// Write dense config vector into Op (zeros other EOM amplitudes first).
  void UnflattenOperator(Operator &Op, const arma::vec &v) const;

  // -----------------------------------------------
  // Lanczos / Arnoldi eigensolver infrastructure
  // (C++ ports of run/lanczos.py)
  // -----------------------------------------------

  // --- norm helpers ---
  double NormSingle(Operator &T1, Operator &T2);
  double NormMultiref(Operator &T1, Operator &T2);
  double Norm3Multiref(Operator &t1, Operator &t2, Operator &haml);

  // --- H * v helpers (direct member calls, no callbacks) ---
  Operator HtcSingle(Operator &haml, Operator &chi);   ///< [Haml,chi] → ladder_single
  Operator HtcMultiref(Operator &haml, Operator &chi); ///< [Haml,chi] → ladder_multiref + ProjectOprator

  // --- double commutator diagonal (223_231 + 223_232 + 223_132) ---
  double DcomMultiref(Operator &haml, Operator &chi);

  /// Rayleigh quotient on working Hs (full decoupled H, vv kept):
  ///   (H1 + H2) / N  == Delta E
  /// with the same H1=Htc / H2=Dcom split as ArnoldiSolve.
  double ExpectationValue(Operator &Psi);

  /// Same as ExpectationValue but forced to use Hs_full.
  /// If use_rdm_norm, H1 and N use NormMultiref (RDM /2) instead of ComputeNorm.
  double ExpectationValueFull(Operator &Psi, bool use_rdm_norm = false);

  Operator &GetHsFull() { return Hs_full; }
  bool HaveHsFull() const { return have_Hs_full; }

  // --- eigensolvers ---
  // SR Lanczos (mirrors sr_eom.py lanczos_proc with htc_single/norm_single)
  std::pair<arma::vec, std::vector<Operator>>
  LanczosSolve(Operator &vi, int max_iter, int state_want);

  struct ArnoldiResult {
    arma::vec   energies;
    arma::mat   eigvecs;
    std::vector<Operator> ritz;
    arma::mat   hall;
    arma::vec   residuals;   ///< beta*|s_mk| estimates for returned roots
    double      max_ortho = 0.0; ///< max |<vi|vj>| i!=j seen during the run
    int         steps = 0;
    bool        converged = false;
    std::string stop_reason;
  };

  struct ArnoldiTraceDiffResult {
    bool   found = false;
    int    step = -1;
    int    i = -1;
    int    j = -1;
    double hall_new = 0.0;
    double hall_old = 0.0;
    double delta_hall = 0.0;
    double h1_sym_new = 0.0;
    double h1_sym_old = 0.0;
    double h2_cross_new = 0.0;
    double h2_cross_old = 0.0;
    double h2_sym_new = 0.0;
    double h2_sym_old = 0.0;
    double h2_diag_i_new = 0.0;
    double h2_diag_j_new = 0.0;
    double h2_diag_i_old = 0.0;
    double h2_diag_j_old = 0.0;
    double max_abs_diff = 0.0;
    double max_rel_diff = 0.0;
  };

  // MR Arnoldi (mirrors mr_eom.py arnoldi_proc with htc_multiref/norm_multiref/dcom)
  ArnoldiResult ArnoldiSolve(Operator &vi, int max_iter, int state_want);

  /// Dense GEP via canonical orthogonalization (Szabo–Ostlund):
  ///   N U = U s → X = U_sub s_sub^{-1/2},
  ///   build hermitized H2,  H̃₂ = Xᵀ H₂ X,  diagonalize H̃₂.
  /// If SetArnoldiUseH3(true): keep the lowest n_h2_subspace H2 eigenvectors,
  ///   build H3 by polarization in that subspace, diagonalize H₂+H₃ there.
  /// Requires ConstructConfigs + ConstructNormMatrix and prepared Hs.
  ArnoldiResult SolveGEPCanonical(int state_want, double eps = 1e-8,
                                  int n_h2_subspace = 50);

  /// MR Arnoldi on full decoupled H (Hs_full): no H_PP/H_QQ split,
  /// no EraseValence, no E_val N shift.
  ///   Krylov matvec = HtcMultiref  (2b piece of [H,χ] only)
  ///   Hall_ab = 1/2 (Htc_ab+Htc_ba) + Dcom polarization   (full Q; default)
  /// so diag(Hall) Ritz values match ExpectationValue.  Eigenvalues = ΔE.
  ArnoldiResult ArnoldiSolveH2(Operator &vi, int max_iter, int state_want);

  // Original (pre-refactor) MR Arnoldi kept for benchmarking.  Same Krylov
  // subspace and matrix elements as ArnoldiSolve, but uses NormMultiref for
  // every inner product, the full polarization formula even on the diagonal
  // (no h2_diag short-circuit), and a plain eig_sym (no symmatu pre-symm).
  // Provided so the user can compare result.hall between the two methods.
  ArnoldiResult ArnoldiSolve_old(Operator &vi, int max_iter, int state_want);

  ArnoldiTraceDiffResult CompareArnoldiHallBuild(Operator &vi, int max_iter,
                                                 double tol = 1e-10);

  /// Read a transition density matrix file and populate a scalar 2-body Operator.
  /// File format (mirrors the Python read_tdm in run/lanczos.py):
  ///   line 0 : J_total (float)
  ///   line 1 : norb (int)
  ///   lines 2..norb+1 : orbit table  "idx n l j2 tz2"
  ///   next line : n_obtd
  ///   n_obtd lines : "_ a b ... rd"  (1-body density matrix elements)
  ///   next line : n_tbtd
  ///   n_tbtd lines : "_ a b c d Jab Jcd ... rd"  (2-body density matrix elements;
  ///                  any columns between Jcd and rd are ignored)
  ///   next line : n_3btd
  ///   n_3btd lines : "_ a b c d e f jab jef jtot ... rd"  (3-body density matrix elements)
  Operator ReadTdm(const std::string &tdm_file);

  /// Write the rdm operator to a file in the exact format ReadTdm reads,
  /// iterating over 3-body channels and kets in native memory order.
  void WriteTdm(const Operator &op, const std::string &filename) const;

  /// Build hs_to_rdm_orb map from modelspace -> rdm_ms (must be called after rdm_ms is set).
  void BuildOrbMap();
  /// 1-body rdm element: translates Hs orbit indices to rdm indices, returns 0 if absent.
  double RdmOB(size_t i_hs, size_t j_hs) const;
  /// 2-body rdm element via J + Hs orbit indices, returns 0 if any orbit absent in rdm.
  double RdmTB_J(double J, size_t a_hs, size_t b_hs, size_t c_hs, size_t d_hs) const;
  /// 3-body rdm element <(ab)^Jab c ; J | rho3 | (de)^Jed f ; J> via Hs orbit indices.
  /// Jab, Jed are integer (not 2*J), twoJ = 2*J_total.
  /// Returns 0 if any orbit is absent in the rdm model space.
  double RdmThreeBody_J(int Jab, size_t a_hs, size_t b_hs, size_t c_hs,
                        int Jed, size_t d_hs, size_t e_hs, size_t f_hs, int twoJ) const;

  /// Convenience result bundle returned by Run().
  struct RunResult {
    double      eref;    ///< reference-state energy = <Hs>_RDM (MR) or ZeroBody (SR)
    ArnoldiResult arnoldi; ///< full Arnoldi output (energies, Ritz vecs, ...)
  };

  /// Unified EOM solve — dispatches on is_multiref:
  ///
  ///  SR (is_multiref == false, mirrors run/sr_eom.py):
  ///    Calls force_decouple, builds a random single-ref initial vector,
  ///    then runs LanczosSolve with HtcSingle / NormSingle.
  ///    RunResult::eref = Hs.ZeroBody.
  ///
  ///  MR (is_multiref == true):
  ///    force_decouple only (no EraseValence / E_val·N), then
  ///    ConstructConfigs / ConstructNormMatrix / ConstructProjectMatrix,
  ///    random projected multiref initial vector, ArnoldiSolveH2 on full H.
  ///    RunResult::eref = <Hs>_RDM; Arnoldi eigenvalues are Delta E.
  ///
  /// @param max_iter   maximum Lanczos/Arnoldi steps  (default 200)
  /// @param state_want number of lowest eigenvalues to target (default 6)
  RunResult Run(int max_iter = 200, int state_want = 6);

private:
  static double Norm_abc(size_t p, size_t q, size_t r);
  double ThreeBody_Diagram_Entries_Internal(size_t a, size_t b, size_t c,
                                            size_t d, size_t e, size_t f,
                                            size_t g, double j0, double j2);
  RunResult RunSR(int max_iter, int state_want);  ///< called by Run() when !is_multiref
  RunResult RunMR(int max_iter, int state_want);  ///< called by Run() when  is_multiref
};

#endif
